import type {
  ChannelSnapshot,
  RoomSnapshot,
  TimelineResponse,
  AnomalyResponse,
  PolicyResponse,
} from '../lib/classroom-types'
/** Deterministic TEST fixtures only. Production UI always reads authenticated APIs. */
export const channelFixture = (overrides: Partial<ChannelSnapshot> = {}): ChannelSnapshot => ({
  channel_id: 'channel:test:plug:relay.1',
  channel_key: 'relay.1',
  device_id: 'device:test:plug',
  name: '实验插座',
  kind: 'socket',
  product_family: 'PLUG',
  capabilities: ['relay.commanded', 'relay.feedback'],
  unit: null,
  value: { desired_on: true, output_present: false },
  quality: 'good',
  quality_flags: [],
  observed_at: '2026-10-01T04:00:00Z',
  effective_at: '2026-10-01T04:00:00Z',
  time_basis: 'device_observed',
  measurement_age_ms: null,
  received_at: '2026-10-01T04:00:01Z',
  valid_until: '2026-10-01T04:02:00Z',
  observation_id: 1,
  binding_id: 1,
  source_mode: 'SIMULATED',
  source_version: 'test-v1',
  online_status: 'online',
  feedback_supported: true,
  verification_kind: 'independent_feedback',
  manual_hold_until: null,
  manual_hold_scope: null,
  controllable: true,
  allowed_actions: ['shed', 'restore'],
  block_reason: null,
  ...overrides,
})
export const roomFixture = (overrides: Partial<RoomSnapshot> = {}): RoomSnapshot => ({
  id: 'space:test:101',
  name: '教学楼101',
  kind: 'classroom',
  campus_id: 'campus:test',
  building_id: 'building:test',
  floor_id: 'floor:test:1',
  at: '2026-10-01T04:00:00Z',
  occupancy: 'unknown',
  lighting: 'unknown',
  lighting_verification_kind: 'unknown',
  sockets: 'off',
  observed_power_w: null,
  power_coverage: 0,
  mode: 'manual',
  mode_expires_at: null,
  mode_reason: null,
  source_mode: 'SIMULATED',
  quality: 'unknown',
  channels: [channelFixture()],
  active_anomaly_ids: [],
  planned_occupancy: 0,
  scheduled_titles: [],
  control_authorization: false,
  ...overrides,
})
export const timelineFixture = (): TimelineResponse => ({
  room_id: 'space:test:101',
  start: '2026-10-01T03:00:00Z',
  end: '2026-10-01T04:00:00Z',
  source_modes: ['SIMULATED'],
  semantics: 'Intervals are half-open; unknown remains unknown.',
  intervals: [
    {
      start: '2026-10-01T03:00:00Z',
      end: '2026-10-01T03:01:00Z',
      duration_seconds: 60,
      occupancy: 'occupied',
      lighting: 'on',
      lighting_verification_kind: 'independent_feedback',
      sockets: 'off',
      observed_power_w: 125,
      power_coverage: 1,
      mode: 'manual',
      source_mode: 'SIMULATED',
      quality: 'good',
      observation_ids: [1],
    },
    {
      start: '2026-10-01T03:01:00Z',
      end: '2026-10-01T04:00:00Z',
      duration_seconds: 3540,
      occupancy: 'unknown',
      lighting: 'unknown',
      lighting_verification_kind: 'unknown',
      sockets: 'unknown',
      observed_power_w: null,
      power_coverage: 0,
      mode: 'manual',
      source_mode: 'SIMULATED',
      quality: 'unknown',
      observation_ids: [],
    },
  ],
  durations: {
    occupancy: { occupied: 60, unknown: 3540 },
    lighting: { on: 60, unknown: 3540 },
    sockets: { off: 60, unknown: 3540 },
    mode: { manual: 3600 },
    observed_power_seconds: 60,
    unknown_power_seconds: 3540,
  },
  events: [
    {
      id: 'event:test:1',
      at: '2026-10-01T03:00:00Z',
      type: 'command.requested',
      device_id: 'device:test:plug',
      channel_id: 'channel:test:plug:relay.1',
      command_id: 'command:test:1',
      status: 'requested',
      requested_on: true,
      output_present: null,
      source_mode: 'SIMULATED',
      description: '请求恢复输出',
    },
  ],
})
export const anomalyFixture = (): AnomalyResponse => ({
  id: 'anomaly:test',
  space_id: 'space:test:101',
  campus_id: 'campus:test',
  building_id: 'building:test',
  type: 'power_outlier',
  severity: 'medium',
  status: 'open',
  episode_start: '2026-10-01T03:00:00Z',
  last_observed_at: '2026-10-01T04:00:00Z',
  resolved_at: null,
  source_mode: 'SIMULATED',
  evidence: {
    rule_version: 'rule-test-v1',
    rule_revision: 0,
    clear_threshold_w: null,
    evaluated_at: '2026-10-01T04:00:00Z',
    persistence_seconds: 60,
    required_persistence_seconds: 60,
    observed_power_w: 125,
    threshold_w: null,
    baseline_median_w: null,
    baseline_mad_w: null,
    baseline_sample_count: 2,
    baseline_status: 'insufficient',
    baseline_condition: '同空间同类条件',
    observation_ids: [1, 2],
    quality_flags: ['insufficient_baseline'],
    explanation: '历史样本不足，本次证据不能形成可靠学习基线',
  },
  notes: [],
})
export const policyFixture = (): PolicyResponse => ({
  id: 'policy:test',
  space_id: 'space:test:101',
  campus_id: 'campus:test',
  name: '测试影子计划',
  revision: 1,
  mode: 'SHADOW',
  enabled: true,
  starts_at: '2026-10-01T00:00:00Z',
  ends_at: '2026-10-02T00:00:00Z',
  config: {
    channel_ids: ['channel:test:plug:relay.1'],
    action: 'shed',
    vacant_for_seconds: 300,
    minimum_power_w: 5,
    max_commands: 1,
    reason: '测试策略依据',
  },
  created_by: 'test',
  created_at: '2026-10-01T00:00:00Z',
})
