/** Focused genuine Chromium classroom QA. Local disposable simulation only. */
import fs from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require('playwright');
const [base='http://127.0.0.1:8080', out='/tmp/classroom-browser', fixturePath]=process.argv.slice(2);
if(!/^http:\/\/(127\.0\.0\.1|localhost):\d+$/.test(base)||!fixturePath)throw Error('Explicit local fixture and descriptor required');
const fixture=JSON.parse(await fs.readFile(fixturePath,'utf8'));
if(fixture.seed?.source_mode!=='SIMULATED'||fixture.seed?.version!==3||fixture.rooms!==603)throw Error('Wrong fixture');
await fs.mkdir(out,{recursive:true});
const timeout=Number(process.env.QA_BROWSER_TIMEOUT_MS||180000), readTimeout=Number(process.env.QA_READ_TIMEOUT_MS||600000);
const checks=[],errors=[],responses=[], viewport={width:1920,height:1080};
const phase=(name,extra={})=>console.log(JSON.stringify({phase:name,at:new Date().toISOString(),...extra}));
const save=()=>fs.writeFile(path.join(out,'summary.json'),JSON.stringify({fixture,viewport,fullPage:false,chromiumSandbox:true,traceSnapshots:false,checks,errors,responses},null,2));
const assert=(v,message)=>{if(!v)throw Error(message)};
phase('launch');
const browser=await chromium.launch({headless:true,chromiumSandbox:true,timeout,
 ...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{channel:process.env.QA_BROWSER_CHANNEL||'msedge'}),args:[]});
const context=await browser.newContext({viewport,deviceScaleFactor:1,reducedMotion:'reduce',timezoneId:'Asia/Shanghai'});
// Deliberately no DOM snapshots, video, full-page screenshots or authenticated traces.
const page=await context.newPage();page.setDefaultTimeout(timeout);page.setDefaultNavigationTimeout(readTimeout);
page.on('pageerror',e=>errors.push(e.message));
page.on('response',r=>{if(r.url().includes('/api/'))responses.push({path:new URL(r.url()).pathname,status:r.status()});});
async function check(name,fn){phase('check-start',{name});const at=Date.now();try{checks.push({name,status:'passed',durationMs:Date.now()-at,detail:await fn()});checks.at(-1).durationMs=Date.now()-at;}catch(e){checks.push({name,status:'failed',durationMs:Date.now()-at,error:String(e)});}await save();phase('check-complete',checks.at(-1));}
async function request(route,method='GET',body){const response=await context.request.fetch(base+'/api/v1'+route,{method,timeout:readTimeout,...(body?{data:body,headers:{'X-CSRF-Token':csrf}}:{})});const data=await response.json();assert(response.ok(),`${method} ${route} HTTP${response.status()} ${JSON.stringify(data)}`);return data;}
async function readyChannel(roomId,key){const until=Date.now()+360000;let waiting=false;while(Date.now()<until){const room=(await request('/classrooms/'+roomId)).data;const target=room.channels.find(c=>c.product_family==='SWITCH'&&c.channel_key===key);assert(target?.quality==='good','Fresh target fixture missing');const action=target.value?.actuator_reported_on===false?'restore':'shed';const eligibility=(await request('/devices/'+encodeURIComponent(target.device_id)+'/control-eligibility?channel_id='+encodeURIComponent(target.channel_id))).data;if(eligibility.eligible&&eligibility.allowed_actions.includes(action))return {room,action};assert(eligibility.reasons[action]==='minimum_dwell','Channel not eligible: '+JSON.stringify(eligibility.reasons));if(!waiting){phase('waiting-for-minimum-dwell',{channelId:target.channel_id,maximumSeconds:360});waiting=true;}await new Promise(resolve=>setTimeout(resolve,1000));}throw Error('Minimum dwell remained blocked after bounded wait');}
async function go(route){phase('navigate',{route});await page.goto(base+route,{waitUntil:'domcontentloaded'});await page.locator('#main-content').waitFor({timeout:readTimeout});await page.waitForFunction(()=>!document.querySelector('#main-content .loading-state, #main-content [aria-busy="true"]'),{},{timeout:readTimeout});assert(await page.locator('#main-content > .error-state').count()===0,'Top-level API error');}
async function capture(name){phase('capture-start',{name});const filename=name+'.png';await page.screenshot({path:path.join(out,filename),fullPage:false,animations:'disabled',timeout});phase('capture-done',{name});return filename;}
const id=encodeURIComponent(fixture.room_id), at=encodeURIComponent(fixture.anchor), home='/classrooms/'+id;
let csrf;
try{
 await check('authenticated_fixture_session',async()=>{const r=await context.request.post(base+'/api/v1/auth/login',{data:{username:'admin',password:'development-only'},timeout:readTimeout});assert(r.status()===200,'Fixture login rejected');csrf=(await r.json()).data.csrf_token;const me=(await request('/auth/me')).data;assert(me.user.role==='admin','Wrong session role');return {role:me.user.role,method:'real HTTP login, browser cookie context'};});
 if(checks[0].status!=='passed')throw Error('Authentication prerequisite failed; page groups not run');
 await check('all_application_routes',async()=>{const routes=['/','/campus','/classrooms','/energy','/carbon','/devices','/topology','/alarms','/strategies','/commands','/reports','/schedules','/system'];for(const route of routes){await go(route);assert((await page.locator('#main-content').innerText()).trim().length>0,'Empty application route '+route);}return {routes};});
 await check('public_spatial_metadata_and_list_fallback',async()=>{const manifest=(await request('/assets/manifest')).data;assert(Object.keys(manifest.floorplans||{}).length===0,'Public package unexpectedly includes indoor floorplans');await go('/campus?building='+encodeURIComponent(fixture.building_id)+'&floor='+encodeURIComponent(fixture.floor_id)+'&at='+at);const fallback=page.getByText('该楼层尚无已发布图面',{exact:true});await fallback.waitFor();const room=page.locator('.space-card').filter({hasText:fixture.room_name}).first();assert(await room.count()===1,'Room identity missing from geometry-free list');await fallback.scrollIntoViewIfNeeded();const screenshot=await capture('07-campus-public-metadata-fallback');await room.click();await page.waitForURL(url=>url.searchParams.get('space')===fixture.room_id);return {spatialVersion:manifest.version,roomId:fixture.room_id,floorplanCount:0,listSelectionWorks:true,screenshot};});
 await check('full_603_room_matrix',async()=>{const rooms=await request('/classrooms?limit=2000&at='+at);assert(rooms.meta.total===603&&rooms.data.length===603,'Incomplete room inventory');assert(rooms.data.every(r=>r.source_mode==='SIMULATED'),'Unexpected source');await go('/classrooms?at='+at);await page.locator('.room-tile').first().waitFor();const tiles=await page.locator('.room-tile').count();assert(tiles>0&&tiles<=96,'Expected bounded tile page');return {inventory:rooms.data.length,visibleTilePage:tiles,screenshot:await capture('01-classroom-matrix-603')};});
 await check('room_three_gangs_and_aggregate_only',async()=>{const room=(await request('/classrooms/'+id+'?at='+at)).data;const sw=room.channels.filter(c=>c.product_family==='SWITCH');assert(sw.filter(c=>/^relay\.[123]$/.test(c.channel_key)).length===3,'Missing independently addressed gangs');assert(sw.filter(c=>c.channel_key==='meter.aggregate').length===1,'Missing unique aggregate meter');assert(sw.filter(c=>/^relay\./.test(c.channel_key)).every(c=>c.value?.output_present==null&&c.value?.active_power_w==null),'Invented per-gang physical feedback or power');await go(home+'?at='+at);await page.getByRole('heading',{name:'CARBENTRA Switch',exact:true}).waitFor();const historicalButtons=page.getByRole('button',{name:/^操作 .*relay\.[123]$/});for(let i=0;i<await historicalButtons.count();i++)assert(await historicalButtons.nth(i).isDisabled(),'Historical page enables mutation');await page.getByRole('heading',{name:'教室设备与通道',exact:true}).evaluate(el=>el.scrollIntoView({block:'start',behavior:'instant'}));await page.waitForFunction(()=>{const images=[...document.querySelectorAll('.room-device-grid img')];return images.length===3&&images.every(i=>i.complete&&i.naturalWidth>0)},{},{timeout:readTimeout});return {switchChannels:sw.map(c=>({key:c.channel_key,quality:c.quality,feedback:c.value?.output_present,power:c.value?.active_power_w})),screenshot:await capture('02-classroom-three-gang-home')};});
 await check('observed_timeline_and_unknown_gaps',async()=>{await go(home+'?at='+at+'&tab=history');await page.locator('.room-intervals').waitFor();return {screenshot:await capture('03-classroom-observed-timeline')};});
 await check('persisted_classroom_anomalies',async()=>{const result=await request('/classrooms/anomalies?space_id='+id);assert(result.data.length>0,'Expected deterministic vacant-load episode');await go('/alarms?view=classrooms&space='+id+'&building='+encodeURIComponent(fixture.building_id));return {episodes:result.data.map(r=>({type:r.type,status:r.status,source_mode:r.source_mode})),screenshot:await capture('04-classroom-anomaly-evidence')};});
 await check('channel_action_manual_hold_and_isolation',async()=>{const {room:before,action}=await readyChannel(id,'relay.2');await go(home);const sw=before.channels.filter(c=>c.product_family==='SWITCH');const relay2=sw.find(c=>c.channel_key==='relay.2');assert(relay2?.quality==='good','Fresh target fixture missing');await page.getByRole('button',{name:/^操作 .*relay\.2$/}).click();const dialog=page.getByRole('dialog',{name:/CARBENTRA Switch · relay\.2 通道操作/});await dialog.waitFor();await dialog.getByLabel(/^本次通道动作/).selectOption(action);await dialog.getByLabel(/^通道申请原因/).fill('Disposable classroom browser QA: only relay.2, no real hardware');await dialog.getByLabel(/^此通道人工接管时限/).selectOption('900');await dialog.getByRole('checkbox',{name:/已核对 relay\.2/}).check();const response=page.waitForResponse(r=>r.url().endsWith('/api/v1/commands')&&r.request().method()==='POST',{timeout:readTimeout});await dialog.getByRole('button',{name:'提交此通道申请',exact:true}).click();const sent=await response;assert(sent.ok(),'Channel request rejected '+await sent.text());const command=(await sent.json()).data;let terminal;const deadline=Date.now()+120000;do{terminal=(await request('/commands/'+command.id)).data;if(['acknowledged_unverified','verified','rejected','timed_out','failed'].includes(terminal.status))break;await new Promise(r=>setTimeout(r,1000));}while(Date.now()<deadline);assert(terminal.status==='acknowledged_unverified','Unexpected Switch terminal '+terminal.status);assert(terminal.result==null,'Switch fabricated physical result');const after=(await request('/classrooms/'+id)).data;const ch=key=>after.channels.find(c=>c.device_id===relay2.device_id&&c.channel_key===key);assert(ch('relay.2').value?.actuator_reported_on===(action==='restore'),'Target actuator report does not match requested action');for(const key of ['relay.1','relay.3'])assert(ch(key).value?.actuator_reported_on===sw.find(c=>c.channel_key===key).value?.actuator_reported_on,'Sibling changed: '+key);assert(ch('relay.2').manual_hold_scope==='backend_edge','Manual hold scope missing');await dialog.getByRole('link',{name:'追踪此通道命令'}).click();await page.getByText('执行器已回报，独立物理状态未验证',{exact:true}).waitFor();return {commandId:command.id,action,channelId:terminal.channel_id,status:terminal.status,physicalResult:terminal.result,siblingChannelsUnchanged:true,manualHoldScope:ch('relay.2').manual_hold_scope,screenshot:await capture('05-classroom-channel-command-hold')};});
 await check('bounded_shadow_policy_and_saved_evaluation',async()=>{const room=(await request('/classrooms/'+id)).data;const target=room.channels.find(c=>c.product_family==='SWITCH'&&c.channel_key==='relay.2');const now=Date.now();const policy=(await request('/classrooms/'+id+'/policies','POST',{name:'浏览器验收 · relay.2 离人影子策略 '+new Date(now).toISOString(),mode:'SHADOW',enabled:true,starts_at:new Date(now-60000).toISOString(),ends_at:new Date(now+3600000).toISOString(),channel_ids:[target.channel_id],action:'shed',vacant_for_seconds:300,minimum_power_w:5,max_commands:1,reason:'Disposable local browser evidence; shadow only, no command authorization'})).data;const evaluation=(await request('/classrooms/policies/'+policy.id+'/evaluate','POST',{})).data;assert(evaluation.command_ids.length===0,'Shadow evaluation created commands');await go(home+'?tab=plans');await page.getByText(policy.name,{exact:true}).waitFor();return {policyId:policy.id,evaluationId:evaluation.id,commandIds:evaluation.command_ids,screenshot:await capture('06-classroom-policy-evidence')};});
}finally{await save();await context.close();await browser.close();}
process.exitCode=checks.some(c=>c.status==='failed')||errors.length?1:0;
