"""scoped users and durable adapter evidence
Revision ID: 1b0b4178c284
Revises: e53ed164cd2f
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import app.db

revision: str = '1b0b4178c284'
down_revision: Union[str, None] = 'e53ed164cd2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adapter_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.String(length=80), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('campus_id', sa.String(length=160), nullable=False),
    sa.Column('boot_epoch', sa.String(length=80), nullable=False),
    sa.Column('sequence', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=60), nullable=False),
    sa.Column('source_mode', sa.String(length=20), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('received_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('command_id', 'device_id', 'boot_epoch', 'sequence', 'status', name='uq_observation_identity')
    )
    with op.batch_alter_table('adapter_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adapter_observations_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adapter_observations_command_id'), ['command_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adapter_observations_device_id'), ['device_id'], unique=False)

    op.create_table('simulated_outputs',
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('campus_id', sa.String(length=160), nullable=False),
    sa.Column('output_present', sa.Boolean(), nullable=False),
    sa.Column('desired_on', sa.Boolean(), nullable=False),
    sa.Column('fault_latched', sa.Boolean(), nullable=False),
    sa.Column('pending_command_id', sa.String(length=80), nullable=True),
    sa.Column('requested_monotonic_ms', sa.BigInteger(), nullable=True),
    sa.Column('deadline_monotonic_ms', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('device_id')
    )
    with op.batch_alter_table('simulated_outputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulated_outputs_campus_id'), ['campus_id'], unique=False)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campus_id', sa.String(length=160), nullable=True))
        batch_op.create_index(batch_op.f('ix_audit_log_campus_id'), ['campus_id'], unique=False)

    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campus_id', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('building_id', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('dispatch_mode', sa.String(length=20), nullable=False, server_default='IN_PROCESS'))
        batch_op.add_column(sa.Column('lease_id', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('lease_expires_at', app.db.UTCDateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('expected_boot_epoch', sa.String(length=80), nullable=True))
        batch_op.alter_column('sequence',
               existing_type=sa.INTEGER(),
               type_=app.db.UInt64Counter(length=20),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_commands_campus_id'), ['campus_id'], unique=False)

    op.execute(sa.text("UPDATE commands SET campus_id = (SELECT campus_id FROM devices WHERE devices.id = commands.device_id), building_id = (SELECT building_id FROM devices WHERE devices.id = commands.device_id)"))
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.alter_column('campus_id', existing_type=sa.String(length=160), nullable=False)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dispatch_mode', sa.String(length=20), nullable=False, server_default='IN_PROCESS'))
        batch_op.add_column(sa.Column('physical_release_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('next_command_sequence',
               existing_type=sa.INTEGER(),
               type_=app.db.UInt64Counter(length=20),
               existing_nullable=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campus_id', sa.String(length=160), nullable=True))
        batch_op.create_index(batch_op.f('ix_events_campus_id'), ['campus_id'], unique=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campus_id', sa.String(length=160), nullable=True))
        batch_op.create_index(batch_op.f('ix_reports_campus_id'), ['campus_id'], unique=False)

    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correlation_command_id', sa.String(length=80), nullable=True))
        batch_op.create_index(batch_op.f('ix_telemetry_correlation_command_id'), ['correlation_command_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campus_ids', sa.JSON(), nullable=True))

    # ### end Alembic commands ###

def downgrade() -> None:
    # Older schemas use signed int32. Refuse lossy rollback after uint64 sequences
    # have been used; restore a pre-migration backup instead.
    connection = op.get_bind()
    for table, column in [("devices", "next_command_sequence"), ("commands", "sequence")]:
        values = connection.execute(sa.text(f"SELECT {column} FROM {table}"))
        if any(int(row[0]) > 2147483647 for row in values):
            raise RuntimeError("Unsafe sequence downgrade; restore a verified pre-migration backup")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('campus_ids')

    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telemetry_correlation_command_id'))
        batch_op.drop_column('correlation_command_id')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_campus_id'))
        batch_op.drop_column('campus_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_campus_id'))
        batch_op.drop_column('campus_id')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('next_command_sequence',
               existing_type=app.db.UInt64Counter(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('physical_release_id')
        batch_op.drop_column('dispatch_mode')

    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commands_campus_id'))
        batch_op.alter_column('sequence',
               existing_type=app.db.UInt64Counter(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('expected_boot_epoch')
        batch_op.drop_column('lease_expires_at')
        batch_op.drop_column('lease_id')
        batch_op.drop_column('dispatch_mode')
        batch_op.drop_column('building_id')
        batch_op.drop_column('campus_id')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_campus_id'))
        batch_op.drop_column('campus_id')

    with op.batch_alter_table('simulated_outputs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulated_outputs_campus_id'))

    op.drop_table('simulated_outputs')
    with op.batch_alter_table('adapter_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adapter_observations_device_id'))
        batch_op.drop_index(batch_op.f('ix_adapter_observations_command_id'))
        batch_op.drop_index(batch_op.f('ix_adapter_observations_campus_id'))

    op.drop_table('adapter_observations')
    # ### end Alembic commands ###
