"""channel targeted commands and manual holds
Revision ID: 22dd42bc323d
Revises: 273cb450c2f7
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import app.db

revision: str = '22dd42bc323d'
down_revision: Union[str, None] = '273cb450c2f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulated_channel_outputs',
    sa.Column('channel_id', sa.String(length=200), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('campus_id', sa.String(length=160), nullable=False),
    sa.Column('actuator_reported_on', sa.Boolean(), nullable=False),
    sa.Column('last_command_id', sa.String(length=80), nullable=True),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['device_channels.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('channel_id')
    )
    with op.batch_alter_table('simulated_channel_outputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulated_channel_outputs_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulated_channel_outputs_device_id'), ['device_id'], unique=False)

    op.create_table('channel_holds',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('channel_id', sa.String(length=200), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('campus_id', sa.String(length=160), nullable=False),
    sa.Column('command_id', sa.String(length=80), nullable=False),
    sa.Column('starts_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ends_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['device_channels.id'], ),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('command_id')
    )
    with op.batch_alter_table('channel_holds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_holds_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_holds_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_holds_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_holds_ends_at'), ['ends_at'], unique=False)

    with op.batch_alter_table('channel_acknowledgements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matched', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('channel_key', sa.String(length=100), nullable=False, server_default='relay.1'))
        batch_op.add_column(sa.Column('product_family', sa.String(length=20), nullable=False, server_default='PLUG'))
        batch_op.add_column(sa.Column('manual_hold_seconds', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_commands_channel_id'), ['channel_id'], unique=False)
        batch_op.create_foreign_key('fk_commands_channel', 'device_channels', ['channel_id'], ['id'])

    with op.batch_alter_table('device_channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_control_at', app.db.UTCDateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###

def downgrade() -> None:
    op.drop_table("channel_holds")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_channels', schema=None) as batch_op:
        batch_op.drop_column('last_control_at')

    with op.batch_alter_table('commands', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_commands_channel', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_commands_channel_id'))
        batch_op.drop_column('manual_hold_seconds')
        batch_op.drop_column('product_family')
        batch_op.drop_column('channel_key')
        batch_op.drop_column('channel_id')

    with op.batch_alter_table('channel_acknowledgements', schema=None) as batch_op:
        batch_op.drop_column('matched')

    with op.batch_alter_table('simulated_channel_outputs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulated_channel_outputs_device_id'))
        batch_op.drop_index(batch_op.f('ix_simulated_channel_outputs_campus_id'))

    op.drop_table('simulated_channel_outputs')
    # ### end Alembic commands ###
