"""bounded relative sensing and versioned anomaly rules
Revision ID: 23281196af6d
Revises: 22dd42bc323d
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import app.db

revision: str = '23281196af6d'
down_revision: Union[str, None] = '22dd42bc323d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_anomaly_rules',
    sa.Column('space_id', sa.String(length=200), nullable=False),
    sa.Column('campus_id', sa.String(length=160), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('space_id')
    )
    with op.batch_alter_table('room_anomaly_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_anomaly_rules_campus_id'), ['campus_id'], unique=False)

    with op.batch_alter_table('channel_observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_basis', sa.String(length=50), nullable=False, server_default='device_observed'))
        batch_op.add_column(sa.Column('measured_at', app.db.UTCDateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('measurement_age_ms', sa.Float(), nullable=True))

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_observations', schema=None) as batch_op:
        batch_op.drop_column('measurement_age_ms')
        batch_op.drop_column('measured_at')
        batch_op.drop_column('time_basis')

    with op.batch_alter_table('room_anomaly_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_anomaly_rules_campus_id'))

    op.drop_table('room_anomaly_rules')
    # ### end Alembic commands ###
