"""classroom channel evidence and bounded room operations
Revision ID: 273cb450c2f7
Revises: ba682468c8c6
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import app.db

revision: str = '273cb450c2f7'
down_revision: Union[str, None] = 'ba682468c8c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_anomalies',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('space_id', sa.String(length=200), nullable=False),
    sa.Column('campus_id', sa.String(length=160), nullable=False),
    sa.Column('building_id', sa.String(length=160), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('episode_start', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_observed_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('source_mode', sa.String(length=20), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('space_id', 'type', 'episode_start', name='uq_room_anomaly_episode')
    )
    with op.batch_alter_table('room_anomalies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_anomalies_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_anomalies_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_anomalies_space_id'), ['space_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_anomalies_status'), ['status'], unique=False)

    op.create_table('room_modes',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('space_id', sa.String(length=200), nullable=False),
    sa.Column('campus_id', sa.String(length=160), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('starts_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ends_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_modes', schema=None) as batch_op:
        batch_op.create_index('ix_room_mode_interval', ['space_id', 'starts_at', 'ends_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_modes_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_modes_space_id'), ['space_id'], unique=False)

    op.create_table('room_policies',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('space_id', sa.String(length=200), nullable=False),
    sa.Column('campus_id', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('starts_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ends_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_policies_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_policies_space_id'), ['space_id'], unique=False)

    op.create_table('room_evaluations',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('policy_id', sa.String(length=80), nullable=False),
    sa.Column('space_id', sa.String(length=200), nullable=False),
    sa.Column('campus_id', sa.String(length=160), nullable=False),
    sa.Column('at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('policy_revision', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('command_ids', sa.JSON(), nullable=False),
    sa.Column('dispatched_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['room_policies.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_evaluations_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_evaluations_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_evaluations_policy_id'), ['policy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_evaluations_space_id'), ['space_id'], unique=False)

    op.create_table('channel_acknowledgements',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('campus_id', sa.String(length=160), nullable=False),
    sa.Column('boot_id', sa.String(length=80), nullable=False),
    sa.Column('command_id', sa.String(length=80), nullable=False),
    sa.Column('sequence', sa.String(length=20), nullable=False),
    sa.Column('channel_number', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=40), nullable=False),
    sa.Column('received_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'boot_id', 'command_id', 'sequence', 'channel_number', 'result', name='uq_channel_ack_identity')
    )
    with op.batch_alter_table('channel_acknowledgements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_acknowledgements_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_acknowledgements_command_id'), ['command_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_acknowledgements_device_id'), ['device_id'], unique=False)

    op.create_table('device_channels',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('campus_id', sa.String(length=160), nullable=False),
    sa.Column('channel_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('freshness_seconds', sa.Integer(), nullable=False),
    sa.Column('controllable', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'channel_key', name='uq_device_channel_key')
    )
    with op.batch_alter_table('device_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_channels_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_channels_device_id'), ['device_id'], unique=False)

    op.create_table('hardware_events',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('campus_id', sa.String(length=160), nullable=False),
    sa.Column('boot_id', sa.String(length=100), nullable=False),
    sa.Column('sequence', sa.String(length=20), nullable=False),
    sa.Column('observed_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('server_received_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('source_mode', sa.String(length=20), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'boot_id', 'sequence', name='uq_hardware_event_identity')
    )
    with op.batch_alter_table('hardware_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hardware_events_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hardware_events_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hardware_events_observed_at'), ['observed_at'], unique=False)

    op.create_table('channel_observations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel_id', sa.String(length=200), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('event_id', sa.String(length=200), nullable=True),
    sa.Column('telemetry_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('boot_epoch', sa.String(length=100), nullable=False),
    sa.Column('sample_seq', sa.String(length=20), nullable=False),
    sa.Column('observed_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('received_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('valid_until', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('quality', sa.String(length=20), nullable=False),
    sa.Column('quality_flags', sa.JSON(), nullable=False),
    sa.Column('source_mode', sa.String(length=20), nullable=False),
    sa.Column('source_version', sa.String(length=100), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('campus_id', sa.String(length=160), nullable=False),
    sa.Column('building_id', sa.String(length=160), nullable=True),
    sa.Column('space_id', sa.String(length=200), nullable=True),
    sa.Column('binding_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['binding_id'], ['device_bindings.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['device_channels.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['hardware_events.id'], ),
    sa.ForeignKeyConstraint(['telemetry_id'], ['telemetry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'boot_epoch', 'sample_seq', name='uq_channel_sample')
    )
    with op.batch_alter_table('channel_observations', schema=None) as batch_op:
        batch_op.create_index('ix_channel_observation_lookup', ['channel_id', 'observed_at', 'id'], unique=False)
        batch_op.create_index('ix_channel_observation_room_time', ['space_id', 'observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_observations_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_observations_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_observations_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_observations_device_id'), ['device_id'], unique=False)

    from app.invariants import install_database_invariants
    install_database_invariants(op.get_bind())
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_observations_device_id'))
        batch_op.drop_index(batch_op.f('ix_channel_observations_channel_id'))
        batch_op.drop_index(batch_op.f('ix_channel_observations_campus_id'))
        batch_op.drop_index(batch_op.f('ix_channel_observations_building_id'))
        batch_op.drop_index('ix_channel_observation_room_time')
        batch_op.drop_index('ix_channel_observation_lookup')

    op.drop_table('channel_observations')
    with op.batch_alter_table('hardware_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hardware_events_observed_at'))
        batch_op.drop_index(batch_op.f('ix_hardware_events_device_id'))
        batch_op.drop_index(batch_op.f('ix_hardware_events_campus_id'))

    op.drop_table('hardware_events')
    with op.batch_alter_table('device_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_channels_device_id'))
        batch_op.drop_index(batch_op.f('ix_device_channels_campus_id'))

    op.drop_table('device_channels')
    with op.batch_alter_table('channel_acknowledgements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_acknowledgements_device_id'))
        batch_op.drop_index(batch_op.f('ix_channel_acknowledgements_command_id'))
        batch_op.drop_index(batch_op.f('ix_channel_acknowledgements_campus_id'))

    op.drop_table('channel_acknowledgements')
    with op.batch_alter_table('room_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_evaluations_space_id'))
        batch_op.drop_index(batch_op.f('ix_room_evaluations_policy_id'))
        batch_op.drop_index(batch_op.f('ix_room_evaluations_campus_id'))
        batch_op.drop_index(batch_op.f('ix_room_evaluations_at'))

    op.drop_table('room_evaluations')
    with op.batch_alter_table('room_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_policies_space_id'))
        batch_op.drop_index(batch_op.f('ix_room_policies_campus_id'))

    op.drop_table('room_policies')
    with op.batch_alter_table('room_modes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_modes_space_id'))
        batch_op.drop_index(batch_op.f('ix_room_modes_campus_id'))
        batch_op.drop_index('ix_room_mode_interval')

    op.drop_table('room_modes')
    with op.batch_alter_table('room_anomalies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_anomalies_status'))
        batch_op.drop_index(batch_op.f('ix_room_anomalies_space_id'))
        batch_op.drop_index(batch_op.f('ix_room_anomalies_campus_id'))
        batch_op.drop_index(batch_op.f('ix_room_anomalies_building_id'))

    op.drop_table('room_anomalies')
    # ### end Alembic commands ###
