"""durable idempotent adapter delivery receipts
Revision ID: 31e3c6004866
Revises: bd3b95cce0a7
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import app.db

revision: str = '31e3c6004866'
down_revision: Union[str, None] = 'bd3b95cce0a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_receipt', sa.JSON(), nullable=True))

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_column('delivery_receipt')

    # ### end Alembic commands ###
