"""64-bit lifetime-safe telemetry and audit identities
Revision ID: 4846bf8f8146
Revises: e6638e25c897
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import app.db

revision: str = '4846bf8f8146'
down_revision: Union[str, None] = 'e6638e25c897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        for table in ("login_attempts", "device_bindings", "telemetry", "audit_log", "events", "adapter_observations"):
            op.alter_column(table, "id", existing_type=sa.Integer(), type_=sa.BigInteger(), existing_nullable=False)
            op.execute(sa.text(f"ALTER SEQUENCE IF EXISTS {table}_id_seq AS bigint"))
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commissioning_records', schema=None) as batch_op:
        batch_op.alter_column('binding_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('latest_telemetry_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.alter_column('binding_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    # ### end Alembic commands ###

def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        for table in ("login_attempts", "device_bindings", "telemetry", "audit_log", "events", "adapter_observations"):
            maximum = op.get_bind().scalar(sa.text(f"SELECT MAX(id) FROM {table}"))
            if maximum is not None and maximum > 2147483647:
                raise RuntimeError("Unsafe identity downgrade; restore a verified pre-migration backup")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.alter_column('binding_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('latest_telemetry_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('commissioning_records', schema=None) as batch_op:
        batch_op.alter_column('binding_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
