"""derived forecast hour revisions and bounded analysis jobs
Revision ID: 6d7d7c3c7c86
Revises: e9e552cad7e0
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import app.db

revision: str = '6d7d7c3c7c86'
down_revision: Union[str, None] = 'e9e552cad7e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_dirty_hours',
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('hour_end', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('source_watermark', sa.BigInteger(), nullable=False),
    sa.Column('queued_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('not_before', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('device_id', 'hour_end')
    )
    with op.batch_alter_table('forecast_dirty_hours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecast_dirty_hours_not_before'), ['not_before'], unique=False)

    op.create_table('forecast_hour_revisions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('campus_id', sa.String(length=160), nullable=False),
    sa.Column('building_id', sa.String(length=160), nullable=True),
    sa.Column('circuit_id', sa.String(length=200), nullable=True),
    sa.Column('source_mode', sa.String(length=20), nullable=False),
    sa.Column('scope_key', sa.String(length=64), nullable=False),
    sa.Column('hour_end', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('available_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('computed_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('source_watermark', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'scope_key', 'hour_end', 'content_hash', name='uq_forecast_hour_content')
    )
    with op.batch_alter_table('forecast_hour_revisions', schema=None) as batch_op:
        batch_op.create_index('ix_forecast_hour_lookup', ['device_id', 'hour_end', 'available_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecast_hour_revisions_available_at'), ['available_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecast_hour_revisions_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecast_hour_revisions_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecast_hour_revisions_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecast_hour_revisions_hour_end'), ['hour_end'], unique=False)

    op.create_table('forecast_projection_state',
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('campus_id', sa.String(length=160), nullable=False),
    sa.Column('source_watermark', sa.BigInteger(), nullable=False),
    sa.Column('closed_revision_id', sa.BigInteger(), nullable=False),
    sa.Column('last_projected_hour', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    with op.batch_alter_table('forecast_projection_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecast_projection_state_campus_id'), ['campus_id'], unique=False)

    op.create_table('forecast_runs',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('campus_id', sa.String(length=160), nullable=True),
    sa.Column('authorized_campus_ids', sa.JSON(), nullable=True),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('input_revision', sa.String(length=64), nullable=False),
    sa.Column('result_input_revision', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('started_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('lease_id', sa.String(length=80), nullable=True),
    sa.Column('lease_expires_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    with op.batch_alter_table('forecast_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecast_runs_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecast_runs_lease_expires_at'), ['lease_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecast_runs_status'), ['status'], unique=False)

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forecast_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecast_runs_status'))
        batch_op.drop_index(batch_op.f('ix_forecast_runs_lease_expires_at'))
        batch_op.drop_index(batch_op.f('ix_forecast_runs_campus_id'))

    op.drop_table('forecast_runs')
    with op.batch_alter_table('forecast_projection_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecast_projection_state_campus_id'))

    op.drop_table('forecast_projection_state')
    with op.batch_alter_table('forecast_hour_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecast_hour_revisions_hour_end'))
        batch_op.drop_index(batch_op.f('ix_forecast_hour_revisions_device_id'))
        batch_op.drop_index(batch_op.f('ix_forecast_hour_revisions_campus_id'))
        batch_op.drop_index(batch_op.f('ix_forecast_hour_revisions_building_id'))
        batch_op.drop_index(batch_op.f('ix_forecast_hour_revisions_available_at'))
        batch_op.drop_index('ix_forecast_hour_lookup')

    op.drop_table('forecast_hour_revisions')
    with op.batch_alter_table('forecast_dirty_hours', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecast_dirty_hours_not_before'))

    op.drop_table('forecast_dirty_hours')
    # ### end Alembic commands ###
