"""event time channel introduction boundary
Revision ID: 98f4a5aa6b9d
Revises: 23281196af6d
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import app.db

revision: str = '98f4a5aa6b9d'
down_revision: Union[str, None] = '23281196af6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('introduced_at', app.db.UTCDateTime(timezone=True), nullable=True))

    op.execute(sa.text("UPDATE device_channels SET introduced_at = CASE WHEN (SELECT MIN(observed_at) FROM channel_observations WHERE channel_id = device_channels.id) < created_at THEN (SELECT MIN(observed_at) FROM channel_observations WHERE channel_id = device_channels.id) ELSE created_at END"))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_channels', schema=None) as batch_op:
        batch_op.drop_column('introduced_at')

    # ### end Alembic commands ###
