"""planned schedules and immutable audit history
Revision ID: bd3b95cce0a7
Revises: 1b0b4178c284
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import app.db

revision: str = 'bd3b95cce0a7'
down_revision: Union[str, None] = '1b0b4178c284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_events',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('campus_id', sa.String(length=160), nullable=False),
    sa.Column('building_id', sa.String(length=160), nullable=True),
    sa.Column('space_id', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('starts_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ends_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('planned_occupancy', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=False),
    sa.Column('source_mode', sa.String(length=20), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_events_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_events_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_events_ends_at'), ['ends_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_events_space_id'), ['space_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_events_starts_at'), ['starts_at'], unique=False)

    from app.invariants import install_database_invariants
    install_database_invariants(op.get_bind())
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_events_starts_at'))
        batch_op.drop_index(batch_op.f('ix_schedule_events_space_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_events_ends_at'))
        batch_op.drop_index(batch_op.f('ix_schedule_events_campus_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_events_building_id'))

    op.drop_table('schedule_events')
    # ### end Alembic commands ###
