"""explicit named load commissioning binding
Revision ID: e4c3069282d4
Revises: 4846bf8f8146
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import app.db

revision: str = 'e4c3069282d4'
down_revision: Union[str, None] = '4846bf8f8146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commissioning_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('load_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('load_name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commissioning_records', schema=None) as batch_op:
        batch_op.drop_column('load_name')
        batch_op.drop_column('load_id')

    # ### end Alembic commands ###
