"""initial canonical campus domain
Revision ID: e53ed164cd2f
Revises: 
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import app.db

revision: str = 'e53ed164cd2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=200), nullable=False),
    sa.Column('at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_type'), ['entity_type'], unique=False)

    op.create_table('campuses',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('source_mode', sa.String(length=30), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carbon_factors',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('kg_co2e_per_kwh', sa.Float(), nullable=False),
    sa.Column('valid_from', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('valid_to', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_mode', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=200), nullable=False),
    sa.Column('at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_hash', sa.String(length=64), nullable=False),
    sa.Column('at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_address_hash'), ['address_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_at'), ['at'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('source_mode', sa.String(length=30), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_state',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tariffs',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rate_per_kwh', sa.Float(), nullable=False),
    sa.Column('valid_from', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('valid_to', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_mode', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('is_dev_fixture', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('buildings',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('campus_id', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('centroid', sa.JSON(), nullable=True),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('external_space_id', sa.String(length=160), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('source_mode', sa.String(length=30), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buildings_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_buildings_name'), ['name'], unique=False)

    op.create_table('sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('csrf_token', sa.String(length=80), nullable=False),
    sa.Column('expires_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_expires_at'), ['expires_at'], unique=False)

    op.create_table('floors',
    sa.Column('id', sa.String(length=180), nullable=False),
    sa.Column('building_id', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('floors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_floors_building_id'), ['building_id'], unique=False)

    op.create_table('strategies',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('campus_id', sa.String(length=160), nullable=False),
    sa.Column('building_id', sa.String(length=160), nullable=True),
    sa.Column('target_reduction_pct', sa.Float(), nullable=False),
    sa.Column('max_devices', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('approved_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('latest_evaluation', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('strategy_id', sa.String(length=80), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluations_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('spaces',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('campus_id', sa.String(length=160), nullable=False),
    sa.Column('building_id', sa.String(length=160), nullable=False),
    sa.Column('floor_id', sa.String(length=180), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('confidence', sa.String(length=40), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spaces_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spaces_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spaces_floor_id'), ['floor_id'], unique=False)

    op.create_table('circuits',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('campus_id', sa.String(length=160), nullable=False),
    sa.Column('building_id', sa.String(length=160), nullable=True),
    sa.Column('space_id', sa.String(length=200), nullable=True),
    sa.Column('parent_id', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('meter_device_id', sa.String(length=100), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('source_mode', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['circuits.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('circuits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_circuits_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_circuits_campus_id'), ['campus_id'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('campus_id', sa.String(length=160), nullable=False),
    sa.Column('building_id', sa.String(length=160), nullable=True),
    sa.Column('floor_id', sa.String(length=180), nullable=True),
    sa.Column('space_id', sa.String(length=200), nullable=True),
    sa.Column('circuit_id', sa.String(length=200), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('source_mode', sa.String(length=20), nullable=False),
    sa.Column('commissioned', sa.Boolean(), nullable=False),
    sa.Column('critical', sa.Boolean(), nullable=False),
    sa.Column('allow_control', sa.Boolean(), nullable=False),
    sa.Column('profile_id', sa.String(length=100), nullable=False),
    sa.Column('profile_revision', sa.Integer(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('minimum_dwell_seconds', sa.Integer(), nullable=False),
    sa.Column('last_control_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('next_command_sequence', sa.Integer(), nullable=False),
    sa.Column('latest_telemetry_id', sa.Integer(), nullable=True),
    sa.Column('last_seen_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_circuit_id'), ['circuit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_space_id'), ['space_id'], unique=False)

    op.create_table('alarms',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('campus_id', sa.String(length=160), nullable=False),
    sa.Column('building_id', sa.String(length=160), nullable=True),
    sa.Column('space_id', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_mode', sa.String(length=20), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alarms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alarms_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alarms_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alarms_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alarms_status'), ['status'], unique=False)

    op.create_table('commands',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source_mode', sa.String(length=20), nullable=False),
    sa.Column('issued_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('simulation_scenario', sa.String(length=20), nullable=False),
    sa.Column('profile_revision', sa.Integer(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'sequence', name='uq_command_sequence'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commands_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commands_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_commands_status'), ['status'], unique=False)

    op.create_table('device_bindings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('campus_id', sa.String(length=160), nullable=False),
    sa.Column('building_id', sa.String(length=160), nullable=True),
    sa.Column('floor_id', sa.String(length=180), nullable=True),
    sa.Column('space_id', sa.String(length=200), nullable=True),
    sa.Column('circuit_id', sa.String(length=200), nullable=True),
    sa.Column('valid_from', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('valid_to', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_bindings_device_id'), ['device_id'], unique=False)

    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('boot_epoch', sa.String(length=80), nullable=False),
    sa.Column('sample_seq', sa.String(length=20), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('observed_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('received_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('time_source', sa.String(length=40), nullable=False),
    sa.Column('time_uncertainty_ms', sa.Float(), nullable=True),
    sa.Column('active_power_w', sa.Float(), nullable=True),
    sa.Column('voltage_v', sa.Float(), nullable=True),
    sa.Column('current_a', sa.Float(), nullable=True),
    sa.Column('energy_import_wh', sa.Float(), nullable=True),
    sa.Column('energy_export_wh', sa.Float(), nullable=True),
    sa.Column('board_temperature_c', sa.Float(), nullable=True),
    sa.Column('desired_on', sa.Boolean(), nullable=True),
    sa.Column('output_present', sa.Boolean(), nullable=True),
    sa.Column('fault_latched', sa.Boolean(), nullable=True),
    sa.Column('quality', sa.String(length=30), nullable=False),
    sa.Column('quality_flags', sa.JSON(), nullable=False),
    sa.Column('source_mode', sa.String(length=20), nullable=False),
    sa.Column('source_version', sa.String(length=100), nullable=False),
    sa.Column('campus_id', sa.String(length=160), nullable=False),
    sa.Column('building_id', sa.String(length=160), nullable=True),
    sa.Column('space_id', sa.String(length=200), nullable=True),
    sa.Column('circuit_id', sa.String(length=200), nullable=True),
    sa.Column('binding_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['binding_id'], ['device_bindings.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'boot_epoch', 'sample_seq', name='uq_sample_identity')
    )
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.create_index('ix_telemetry_building_time', ['building_id', 'observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_device_id'), ['device_id'], unique=False)
        batch_op.create_index('ix_telemetry_device_time', ['device_id', 'observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_observed_at'), ['observed_at'], unique=False)

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telemetry_observed_at'))
        batch_op.drop_index('ix_telemetry_device_time')
        batch_op.drop_index(batch_op.f('ix_telemetry_device_id'))
        batch_op.drop_index(batch_op.f('ix_telemetry_campus_id'))
        batch_op.drop_index('ix_telemetry_building_time')

    op.drop_table('telemetry')
    with op.batch_alter_table('device_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_bindings_device_id'))

    op.drop_table('device_bindings')
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commands_status'))
        batch_op.drop_index(batch_op.f('ix_commands_expires_at'))
        batch_op.drop_index(batch_op.f('ix_commands_device_id'))

    op.drop_table('commands')
    with op.batch_alter_table('alarms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alarms_status'))
        batch_op.drop_index(batch_op.f('ix_alarms_device_id'))
        batch_op.drop_index(batch_op.f('ix_alarms_campus_id'))
        batch_op.drop_index(batch_op.f('ix_alarms_building_id'))

    op.drop_table('alarms')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_space_id'))
        batch_op.drop_index(batch_op.f('ix_devices_circuit_id'))
        batch_op.drop_index(batch_op.f('ix_devices_campus_id'))
        batch_op.drop_index(batch_op.f('ix_devices_building_id'))

    op.drop_table('devices')
    with op.batch_alter_table('circuits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_circuits_campus_id'))
        batch_op.drop_index(batch_op.f('ix_circuits_building_id'))

    op.drop_table('circuits')
    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spaces_floor_id'))
        batch_op.drop_index(batch_op.f('ix_spaces_campus_id'))
        batch_op.drop_index(batch_op.f('ix_spaces_building_id'))

    op.drop_table('spaces')
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluations_strategy_id'))

    op.drop_table('evaluations')
    op.drop_table('strategies')
    with op.batch_alter_table('floors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_floors_building_id'))

    op.drop_table('floors')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_expires_at'))

    op.drop_table('sessions')
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buildings_name'))
        batch_op.drop_index(batch_op.f('ix_buildings_campus_id'))

    op.drop_table('buildings')
    op.drop_table('users')
    op.drop_table('tariffs')
    op.drop_table('system_state')
    op.drop_table('reports')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_at'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_address_hash'))

    op.drop_table('login_attempts')
    op.drop_table('events')
    op.drop_table('carbon_factors')
    op.drop_table('campuses')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
