"""operator evidence releases and account-aware throttling
Revision ID: e6638e25c897
Revises: 31e3c6004866
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import app.db

revision: str = 'e6638e25c897'
down_revision: Union[str, None] = '31e3c6004866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commissioning_records',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('campus_id', sa.String(length=160), nullable=False),
    sa.Column('binding_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.String(length=47), nullable=False),
    sa.Column('hardware_revision', sa.String(length=80), nullable=False),
    sa.Column('safety_assessment_ref', sa.String(length=1000), nullable=False),
    sa.Column('installation_approval_ref', sa.String(length=1000), nullable=False),
    sa.Column('calibration_ref', sa.String(length=1000), nullable=False),
    sa.Column('valid_until', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('released_by', sa.String(length=100), nullable=True),
    sa.Column('released_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['binding_id'], ['device_bindings.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commissioning_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commissioning_records_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commissioning_records_device_id'), ['device_id'], unique=False)

    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_login_attempts_account_hash'), ['account_hash'], unique=False)

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_account_hash'))
        batch_op.drop_column('account_hash')

    with op.batch_alter_table('commissioning_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commissioning_records_device_id'))
        batch_op.drop_index(batch_op.f('ix_commissioning_records_campus_id'))

    op.drop_table('commissioning_records')
    # ### end Alembic commands ###
