"""timezone-aware daily time-of-use rates
Revision ID: e9e552cad7e0
Revises: e4c3069282d4
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import app.db

revision: str = 'e9e552cad7e0'
down_revision: Union[str, None] = 'e4c3069282d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=80), nullable=False, server_default='Asia/Shanghai'))
        batch_op.add_column(sa.Column('bands', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.drop_column('bands')
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
